version: '3.8'

services:

  findfulapi:
    build: ./API/findfulapi:tag
    restart: always
    ports:
       - 44341:44341
    environment:
        DB_URL: FindFulConnection/findfulsql

  findfulclient:
    build: ./client
    ports:
      - 4200:4200

  findfulsql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
        ACCEPT-EULA: "Y"
        MSSQL-SA-PASSOWRD: 
        MSSQL-TCP-PORT: 1443
    ports:
        - "1433:1433"
